version: '2.3'
services:
  app-backend:
    image: "$name;format="normalize"$-api:\${GIT_COMMIT}"
    build:
      context: ./app-backend/api
      dockerfile: Dockerfile
  app-backend-migrations:
    image: "$name;format="normalize"$-api-migrations:\${GIT_COMMIT}"
    build:
      context: ./app-backend/database
      dockerfile: Dockerfile.migrations
